### ISSUE TITLE
Configurations with (multiple?) slash-wrapped regular expressions fail to parse

### ISSUE THREAD

**Issue by backspace** [travis-ci/travis-conditions#10]
This is a continuation from #7. I’ve been experimenting with various `.travis.yml`s and it seems that the presence of wrapping `/…/`s causes parsing failures that are [not mentioned in the documentation](https://docs.travis-ci.com/user/conditions-v1#regular-expressions).

For instance, in [this commit](https://github.com/backspace/travixperiments-redux/compare/d11d9fe8554c...014497b85f63), I changed the stages configuration to this:

```
stages:
  - name: Jorts
    if: type = cron OR commit_message =~ /jortleby/ OR (tag IS present AND tag =~ /^hello$/)
```

The key change is that I added the wrapping `/` around `jortleby`. This causes the request to be rejected as unparseable.

Variations that work:

```
    if: type = cron OR commit_message =~ /jortleby/ OR (tag IS present AND tag IS present)
```

and

```
    if: type = cron OR commit_message =~ /jortleby/ OR (tag IS present AND tag =~ ^hello)
```

So to me it seems like there’s something special about having more than one `/…/` regular expression in a condition.

**Comment by svenfuchs** [comment]
thanks for reporting @backspace! ❤️ 

i believe this should be fixed in https://github.com/travis-ci/travis-conditions/pull/12 

i'm probably missing something. is this issue #10 here the same as #11? 

(btw i think you might be interested to learn about https://github.com/travis-ci/docs-travis-ci-com/pull/1978 for debugging/experimenting with conditions)

**Comment by backspace** [comment]
Thank you!

You’re correct, `eval` and `parse` are news to me, and would be quite helpful for this kind of thing, thanks. I dream of someday having [this](https://github.com/travis-pro/post-its/issues/460) 🤞🏻
