### ISSUE TITLE
Invalid 'echo' example in docs and CLI help

### ISSUE THREAD

**Issue by ulope** [travis-ci/travis-conditions#5]
The [docs](https://docs.travis-ci.com/user/conditions-testing) and CLI help both give the following as an example:
```shell
travis-conditions echo '{"branch": "master"}' | travis-conditions "branch = master"
```

Clearly, that is wrong and should instead be:

```shell
echo '{"branch": "master"}' | travis-conditions "branch = master"
```
 (i.e. drop the first `travis-conditions`)

**Comment by svenfuchs** [comment]
thanks for the report @ulope 

this will be addressed in https://github.com/travis-ci/travis-conditions/pull/12 and  https://github.com/travis-ci/docs-travis-ci-com/pull/1978
